spring:
  datasource:
    jndi-name: jdbc/BolivarianoDS
#    url: jdbc:mysql://181.49.114.18:3306/tarifas?useSSL=false
#    username: root
#    password: root
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
application: 
  topic-name: bolivariano.tarifas
  rabbit:
#    addresses: 181.49.114.18:5672
    addresses: localhost:5672
    user: bolivariano
    pass: bolivariano
